version: 3
endpoint: http://localhost:8080
admin_secret: GnTCxnsmYWLy7qDXzR8LfwXULEcyr3JnThh3SXSd3
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: http://localhost:3000
