version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.0.7
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
volumes:
  db_data:
