version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "15432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:latest.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    #restart: always
    environment:
      HASURA_GRAPHQL_CLI_ENVIRONMENT: "default"
      ENV HASURA_GRAPHQL_CLI_ENVIRONMENT: "default"
      HASURA_GRAPHQL_METADATA_DATABASE_URL: "postgres://postgres:postgrespassword@postgres:5432/postgres"
      ENV HASURA_GRAPHQL_MIGRATIONS_DATABASE_ENV_VAR: "postgres://postgres:postgrespassword@postgres:5432/postgres"
      HASURA_GRAPHQL_DATABASE_URL : "postgres://postgres:postgrespassword@postgres:5432/postgres"
      PG_DATABASE_URL: "postgres://postgres:postgrespassword@postgres:5432/postgres"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_LOG_LEVEL: "warn"
#      HASURA_GRAPHQL_ADMIN_SECRET: "my-admin-secret-you-should-change-this"
      HASURA_GRAPHQL_ENDPOINT: "http://localhost:8080"
#    env_file:
#      - ../.env
#    volumes:
#      - ./migrations:/hasura-migrations
#      - ./metadata:/hasura-metadata
volumes:
  db_data:
